### ISSUE TITLE
[Commit] 

### ISSUE THREAD

**Issue by matyo91** [harshil1712/oss-commit#4]
### Twitter Handler

matyo91

### Commit Goals

256

### Pull Request Goals

16

### Issue Goals

8

**Comment by harshil1712** [comment]
Hey @matyo91 👋

Welcome to OSS Commit!

Thank you for participating and contributing to open-source! Let's make this world a better place ✨

If you have any questions or feedback, feel free to open a new [Discussion topic](https://github.com/harshil1712/oss-commit/discussions/new).

Have a wonderful time!

[Tweet](https://twitter.com/intent/tweet?original_referer=https://github.com/harshil1712/oss-commit&text=For%202022%2C%20I%20will%20be%20contributing%20to%20open-source!%20%0A%0AMy%20goals%3A%0A%F0%9F%92%BB%20256%20commits%0A%F0%9F%90%9B%208%20issues%0A%F0%9F%92%AA%2016%20PR%0A%0ALet%27s%20do%20it%20together!%20Join%20me%20and%20participate%20in%20%23OSSCommit%0A&url=https://github.com/harshil1712/oss-commit)!
